# vgs_python_demo base container
FROM quay.io/verygoodsecurity/pythonbase:latest 

WORKDIR /opt/app/src
ADD  . /opt/app/src
VOLUME /opt/app/src

# install pip ( in separate dir due to docker cache)
ADD setup.py /opt/app
RUN cd /opt/app && pip install -e .

# install nodejs dependencies ( in separate dir due to docker cache)
ADD package.json /opt/app
RUN cd /opt/app && npm install

# this is for virtual host purposes
EXPOSE 3000 3001 8080 5000
CMD ["python", "demo/app.py"]
